minitrack.settings:
  type: config_entity
  mapping:
    api_keys:
      type: sequence
      sequence:
        type: string
    cors_origins:
      type: sequence
      sequence:
        type: string
    retention_days:
      type: integer
